name: dbhdistfit-hps
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - pyarrow
  - jupyterlab
  - notebook
  - pip:
      - lmfit
